# Generated by Django 5.2.7 on 2025-12-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSDairy', '0003_rfidscan_updated_at_alter_rfidscan_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidscan',
            name='direction',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='OUT', max_length=3),
        ),
        migrations.AlterField(
            model_name='rfidscan',
            name='uid',
            field=models.CharField(max_length=50),
        ),
    ]
