# Generated by Django 5.2.7 on 2026-01-26 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSDairy', '0006_block_cow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('active_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSSDairy.block')),
            ],
        ),
    ]
